/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.h2jinee.http.client;

import java.io.*;
import java.net.Socket;
import java.nio.CharBuffer;

public class App {
    public static void main(String[] args) throws IOException {
        App app = new App();
        app.run();
    }

    private void run() throws IOException {
        System.out.println("Hello, world!");

        // 1. Connect

        try (Socket socket = new Socket("example.com", 80)) {
            System.out.println("Connect!");

            // 2. Request

            String message = "" +
                    "GET / HTTP/1.1\n" +
                    "Host: example.com\n" +
                    "\n";

            OutputStream outputStream = socket.getOutputStream();
            Writer writer = new OutputStreamWriter(outputStream);

            writer.write(message);
            writer.flush();

            System.out.println("Request!");

            // 3. Response

            InputStream inputStream = socket.getInputStream();
            Reader reader = new InputStreamReader(inputStream);

            CharBuffer charBuffer = CharBuffer.allocate(1_000_000);

            reader.read(charBuffer);

            charBuffer.flip();

            String text = charBuffer.toString();

            System.out.println(text);

        }

        // 4. Close

        System.out.println("Complete!");

    }
}
